name: test

on:
  push:
    branches:
      - master
  pull_request:


permissions:
  contents: read


jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Set up Python 3.13.2
        uses: actions/setup-python@v5
        with:
          python-version: "3.13.2"
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Check Ruff
        run: python -m ruff check
